import AppShell from "@/components/layouts/AppShell";
import ScrollToTop from "@/components/share/ScrollToTop";
import { ThemeProvider } from "@/components/share/ThemeProvider";
import {
  Bricolage_Grotesque,
  Geist,
  Geist_Mono,
  Gravitas_One,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gravitasOne = Gravitas_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gravitas-one",
  display: "swap",
});

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bricolage",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="scroll-smooth antialiased"
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gravitasOne.variable}  antialiased min-h-screen flex flex-col bg-background text-foreground transition-colors duration-300 ease-in-out`}
      >
        <ScrollToTop />
        <ThemeProvider>
          <AppShell>{children}</AppShell>
        </ThemeProvider>
      </body>
    </html>
  );
}
